parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'

  - template: qt-wrapper-install.yml

  - script: python -m pip install -r tests/ci_requirements.txt
    displayName: 'Install tests dependencies'

  # This runs the tests and redirects the output to test_output.txt
  - bash: python -m coverage run tests/run_tests.py 2>&1 | tee -a $(Build.ArtifactStagingDirectory)/test_output.txt
    displayName: 'Running tests'
    env:
      SHOTGUN_TEST_LOG_FILE_LOCATION: $(Build.ArtifactStagingDirectory)/toolkit_logs_output.txt

  - task: PublishBuildArtifacts@1
    displayName: Upload test output and logs
    condition: succeededOrFailed()
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: test-log-and-output

  - bash: bash <(curl -s https://raw.githubusercontent.com/jfboismenu/azure-pipeline-test/make-cov-work/codecov.sh) -t $(codecov.token)
    condition: succeededOrFailed()
    displayName: 'Uploading coverage to Codecov'