parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
    maxParallel: 1
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'


# These steps could be exported as a InstallPySide template task
  - bash: sudo apt-get install libqt4-dev
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: "Installing Qt on Linux"
    
  - bash: brew tap cartr/qt4 && brew tap-pin cartr/qt4 && brew install qt@4
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: "Installing Qt on Darwin"
    
  - bash: python -m pip install PySide==1.2.2 --no-index --find-links https://parkin.github.io/python-wheelhouse
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: "Installing PySide on Linux"
    
  - script: python -m pip install PySide==1.2.2
    condition: in( variables['Agent.OS'], 'Windows_NT', 'Darwin' )
    displayName: "Installing PySide Windows and macOS"
    
  - bash: pyside_postinstall.py -install
    condition: in( variables['Agent.OS'], 'Linux', 'Darwin' )
    displayName: "PySide post-install on Linux and Darwin"
    
  - bash: |
      export DISPLAY=:99.0
      sh -e xvfb start
      sleep 3
      export QT_QPA_PLATFORM=offscreen
    condition: in( variables['Agent.OS'], 'Linux' )
    displayName: "Prepping XServer"
# End of PySide installation

  - script: python -m pip install -r tests/ci_requirements.txt
    displayName: 'Install dependencies'

  - bash: |
      export QT_QPA_PLATFORM=offscreen
      export DISPLAY=:99.0
      coverage run tests/run_tests.py
    displayName: 'Running tests'
