#!/usr/bin/env bash
#
# Copyright (c) 2012 Shotgun Software, Inc
# ----------------------------------------------------


# get absolute location of this script
SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(basename -- "$0")
 
# resolve symlinks
while [ -h $SELF_PATH ]; do
    # 1) cd to directory of the symlink
    # 2) cd to the directory of where the symlink points
    # 3) get the pwd
    # 4) append the basename
    DIR=$(dirname -- "$SELF_PATH")
    SYM=$(readlink $SELF_PATH)
    SELF_PATH=$(cd $DIR && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
done

# chop off the file name
SELF_PATH=$(dirname $SELF_PATH)

# if we have a local install of the core, this is the script to dispatch to
LOCAL_SCRIPT="$SELF_PATH/install/core/scripts/tank_cmd.sh"

if [ -f "$LOCAL_SCRIPT" ];
then
   # run local script
   $LOCAL_SCRIPT "$SELF_PATH" $@
else
   # there is no local install
   # so try and get the parent and call its tank script
   # the parent location is stored in a config file
   curr_platform=`uname`
   parent_config_file="$SELF_PATH/install/core/core_${curr_platform}.cfg"

   if [ ! -f "$parent_config_file" ];
   then
      echo "Cannot find parent configuration file $parent_config_file!"
      exit 1
   fi
   
   # now get path to parent
   parent_location=`cat "$parent_config_file"`
   # and check that it exists...
   if [ ! -d "$parent_location" ];
   then
      echo "Cannot find parent $parent_location defined in config file $parent_config_file!"
      exit 1
   fi
   
   # all good, execute tank script in parent location
   #$parent_location/tank $@ --pc="$SELF_PATH"
   $parent_location/tank $@
      
fi


