

help:
	@echo clean
	@echo print

clean:
	@echo 'Cleaning Shotgun Cache'
	@rm -rvf ~/Library/Caches/Shotgun/*

print:
	@echo 'Content of Shotgun Cache'
	@find ~/Library/Caches/Shotgun -type f -print0 | xargs -0 cat